
const WHATSAPP='201130102500';
let currentLang='ar';
const products=[
 {id:'sunny-menia',discount:true,ar:'رخام صني منيا',en:'Sunny Menia Marble',img:'sunny-menia.jpg',arDesc:'رخام مصري بيج دافئ من أشهر الخامات المطلوبة في الأرضيات والحوائط والسلالم، يتميز بدرجاته الهادئة وقابليته للتشطيب بأكثر من شكل، ويمنح المساحات إحساسًا بالاتساع والفخامة.',enDesc:'A warm beige Egyptian marble, highly popular for floors, walls and stairs. Its calm tone and flexible finishes create a bright, spacious and elegant atmosphere.'},
 {id:'galala',ar:'رخام جلالة',en:'Galala Marble',img:'galala.jpg',arDesc:'رخام مصري بلون كريمي فاتح ومظهر كلاسيكي راقٍ، مناسب للمشاريع السكنية والتجارية والواجهات الداخلية والأرضيات، ويتميز بسهولة تنسيقه مع الديكورات الحديثة والكلاسيكية.',enDesc:'A light creamy Egyptian marble with a classic elegant look, ideal for residential and commercial projects, interior cladding and flooring.'},
 {id:'silvia',ar:'رخام سلفيا',en:'Silvia Marble',img:'silvia.jpg',arDesc:'رخام مصري بعروق طبيعية ناعمة وملمس فاخر، مناسب للأرضيات والحوائط وأسطح الاستقبال والمشاريع التي تحتاج إلى مظهر دافئ مع قوة عملية.',enDesc:'An Egyptian marble with soft natural veins and a refined texture, suitable for floors, walls, reception counters and warm luxurious interiors.'},
 {id:'cresta',ar:'رخام كريستا',en:'Cresta Marble',img:'cresta.jpg',arDesc:'خامة رخامية بدرجات هادئة وعروق مميزة، تضيف لمسة طبيعية للمساحات الداخلية، وتناسب الأرضيات والحوائط والديكورات التي تعتمد على الفخامة الهادئة.',enDesc:'A calm-toned marble with distinctive veins, adding a natural luxury touch to interiors, walls, floors and refined decoration.'},
 {id:'natural-marble',ar:'رخام طبيعي',en:'Natural Marble',img:'natural-marble.jpg',arDesc:'رخام طبيعي مختار بعناية من المحاجر المصرية، يجمع بين الجمال والقوة ويستخدم في الأرضيات والحوائط والسلالم والتصميمات المعمارية المتنوعة.',enDesc:'Carefully selected natural marble from Egyptian quarries, combining beauty and strength for floors, walls, stairs and architectural applications.'},
 {id:'granite',ar:'جرانيت',en:'Granite',img:'granite.jpg',arDesc:'الجرانيت خيار قوي وعملي للمطابخ والأرضيات والأماكن الأكثر استخدامًا، يتميز بصلابة عالية وتنوع ألوانه وقدرته على تحمل الاستخدام اليومي.',enDesc:'Granite is a strong practical choice for kitchens, floors and high-traffic areas, known for durability, color variety and daily-use resistance.'},
 {id:'marble-slabs',ar:'ألواح رخام',en:'Marble Slabs',img:'marble-slabs.jpg',arDesc:'ألواح كبيرة يتم تجهيزها للمشاريع والفنادق والفلل، وتوفر مظهرًا متصلًا وفاخرًا للحوائط والأرضيات والأسطح حسب المقاسات المطلوبة.',enDesc:'Large slabs prepared for projects, hotels and villas, offering a continuous premium look for walls, floors and surfaces.'},
 {id:'tiles',ar:'بلاط رخام',en:'Marble Tiles',img:'tiles.jpg',arDesc:'بلاط رخام بمقاسات متعددة حسب الطلب، مناسب للأرضيات والحوائط ويمنح تنفيذًا منظمًا وسهل التركيب للمساحات السكنية والتجارية.',enDesc:'Marble tiles in multiple custom sizes, suitable for floors and walls with organized installation for residential and commercial spaces.'},
 {id:'stairs',ar:'درجات سلالم',en:'Stair Steps',img:'stairs.jpg',arDesc:'درجات سلالم رخام وجرانيت بتشطيب عملي وفاخر، مناسبة للمداخل والعمائر والفلل مع قص دقيق حسب المقاسات المطلوبة.',enDesc:'Marble and granite stair steps with practical premium finishing, suitable for entrances, buildings and villas with precise custom cutting.'},
 {id:'facades',ar:'واجهات خارجية',en:'Exterior Facades',img:'facades.jpg',arDesc:'حلول رخام وجرانيت للواجهات الخارجية تضيف قوة ومظهرًا معماريًا مميزًا، مع اختيار خامات تتحمل طبيعة الاستخدام الخارجي.',enDesc:'Marble and granite solutions for exterior facades, adding strength and a distinctive architectural appearance.'},
 {id:'kitchens',ar:'مطابخ وأسطح',en:'Kitchens & Countertops',img:'kitchens.jpg',arDesc:'أسطح مطابخ من الجرانيت والرخام بتشطيبات أنيقة وعملية، تناسب الاستخدام اليومي وتضيف قيمة جمالية عالية للمطبخ.',enDesc:'Kitchen countertops from granite and marble with elegant practical finishes for daily use and premium visual value.'}
];
const grid=document.getElementById('productsGrid');
function t(ar,en){return currentLang==='ar'?ar:en}
function renderProducts(){grid.innerHTML='';products.forEach(p=>{const card=document.createElement('article');card.className='product-card reveal '+(p.discount?'discount':'');card.innerHTML=`<span class="discount-badge">${t('يوجد خصم','Discount Available')}</span><img src="${p.img}" alt="${t(p.ar,p.en)}"><div class="product-info"><h3>${t(p.ar,p.en)}</h3><p>${t(p.arDesc,p.enDesc).slice(0,125)}...</p><button class="primary-btn mini-buy">${t('شراء عبر واتساب','Order on WhatsApp')}</button></div>`;card.addEventListener('click',e=>{if(e.target.classList.contains('mini-buy')){openWhatsAppProduct(p);return}openProductModal(p)});grid.appendChild(card)});observeReveal()}
const productModal=document.getElementById('productModal'),modalImage=document.getElementById('modalImage'),modalTitle=document.getElementById('modalTitle'),modalDesc=document.getElementById('modalDesc'),modalDiscount=document.getElementById('modalDiscount'),modalBuy=document.getElementById('modalBuy');
let activeProduct=null;
function openProductModal(p){activeProduct=p;modalImage.src=p.img;modalTitle.textContent=t(p.ar,p.en);modalDesc.textContent=t(p.arDesc,p.enDesc);modalDiscount.classList.toggle('show',!!p.discount);productModal.classList.add('active');productModal.setAttribute('aria-hidden','false')}
function closeProductModal(){productModal.classList.remove('active');productModal.setAttribute('aria-hidden','true')}
function openWhatsAppProduct(p){const msg=currentLang==='ar'?`مرحباً، أريد شراء / الاستفسار عن منتج: ${p.ar}`:`Hello, I want to order/inquire about: ${p.en}`;window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(msg)}`,'_blank')}
modalBuy.addEventListener('click',()=>{if(activeProduct)openWhatsAppProduct(activeProduct)});
document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',closeProductModal));
const quoteModal=document.getElementById('quoteModal');document.querySelectorAll('[data-open-quote]').forEach(btn=>btn.addEventListener('click',()=>{quoteModal.classList.add('active');quoteModal.setAttribute('aria-hidden','false')}));document.querySelectorAll('[data-close-quote]').forEach(btn=>btn.addEventListener('click',()=>{quoteModal.classList.remove('active');quoteModal.setAttribute('aria-hidden','true')}));
document.getElementById('quoteForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target);const msg=currentLang==='ar'?`طلب عرض سعر من موقع الصرح%0Aالاسم: ${d.get('name')}%0Aالهاتف: ${d.get('phone')}%0Aالبريد: ${d.get('email')||'غير مذكور'}%0Aالكمية: ${d.get('quantity')}%0Aالسعر المتوقع: ${d.get('price')||'غير مذكور'}%0Aالمطلوب / الملاحظات: ${d.get('notes')||'لا يوجد'}`:`Quote request from Al Sarh website%0AName: ${d.get('name')}%0APhone: ${d.get('phone')}%0AEmail: ${d.get('email')||'Not provided'}%0AQuantity: ${d.get('quantity')}%0AExpected price: ${d.get('price')||'Not provided'}%0ARequest / Notes: ${d.get('notes')||'None'}`;window.open(`https://wa.me/${WHATSAPP}?text=${msg}`,'_blank')});
function setLang(lang){currentLang=lang;document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.getElementById('langToggle').textContent=lang==='ar'?'EN':'AR';document.querySelectorAll('[data-ar]').forEach(el=>{el.textContent=lang==='ar'?el.dataset.ar:el.dataset.en});document.querySelectorAll('[data-ar-placeholder]').forEach(el=>{el.placeholder=lang==='ar'?el.dataset.arPlaceholder:el.dataset.enPlaceholder});renderProducts();}
document.getElementById('langToggle').addEventListener('click',()=>setLang(currentLang==='ar'?'en':'ar'));
document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('navLinks').classList.toggle('active'));document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>document.getElementById('navLinks').classList.remove('active')));
function animateCounts(){document.querySelectorAll('[data-count]').forEach(el=>{if(el.dataset.done)return;const end=+el.dataset.count;let current=0;const step=Math.max(1,Math.floor(end/60));const timer=setInterval(()=>{current+=step;if(current>=end){current=end;clearInterval(timer);el.dataset.done='1'}el.textContent=current.toLocaleString(currentLang==='ar'?'ar-EG':'en-US')},24)})}
function animateBars(){document.querySelectorAll('.client-row').forEach(row=>{if(row.dataset.done)return;const span=row.querySelector('.bar span');span.style.width=row.dataset.percent+'%';row.dataset.done='1'})}
let observer;function observeReveal(){if(observer)observer.disconnect();observer=new IntersectionObserver(entries=>{entries.forEach(en=>{if(en.isIntersecting){en.target.classList.add('visible');if(en.target.classList.contains('stats-grid')||en.target.closest('.stats'))animateCounts();if(en.target.classList.contains('client-bars')||en.target.closest('.clients'))animateBars();}})},{threshold:.18});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}
window.addEventListener('scroll',()=>{document.getElementById('navbar').classList.toggle('scrolled',scrollY>30)});
renderProducts();setLang('ar');observeReveal();
